version: '3.7'

services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./src/main/resources/docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql
